version: '3.7'

services:
  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    image: amd64/nginx:stable-alpine
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8091:8091"
    volumes:
      - "${DOCKER_ENV_PATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${API_PATH}:${API_WORKDIR}"
    links:
      - api
      - frontend

  api:
    container_name: "${PROJECT_NAME}_api"
    build:
      context: ./
      dockerfile: "${DOCKER_ENV_PATH}/php${PHP_VERSION}-fpm/Dockerfile"
      args:
        workdir: ${API_WORKDIR}
        app_path: ${API_PATH}
    platform: linux/amd64
    expose:
      - "9001"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - "${API_PATH}:${API_WORKDIR}"
      - "${DOCKER_ENV_PATH}/php${PHP_VERSION}-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
    links:
      - postgres

  postgres:
    container_name: "${PROJECT_NAME}_postgres"
    image: postgres:14.2
    restart: unless-stopped
    platform: linux/amd64
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - "${DATA_PATH}/postgres/data:/var/lib/postgresql/data/"

  frontend:
    container_name: "${PROJECT_NAME}_frontend"
    build:
      context: ./
      dockerfile: "${DOCKER_ENV_PATH}/frontend/Dockerfile"
    platform: linux/amd64
    volumes:
      - "./frontend:/usr/src/frontend"
    ports:
      - "3001:3001"
    restart: unless-stopped

  parser:
    container_name: "${PROJECT_NAME}_parser"
    build:
      context: ./
      dockerfile: "${DOCKER_ENV_PATH}/php${PHP_VERSION}-fpm/Dockerfile"
      args:
        workdir: ${API_WORKDIR}
        app_path: ${API_PATH}
    platform: linux/amd64
    expose:
      - "9001"
    volumes:
      - "${API_PATH}:${API_WORKDIR}"
      - "${DOCKER_ENV_PATH}/php${PHP_VERSION}-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
    command: sh -c "sleep 30 && bin/console --no-debug -q app:worker:parser"
    restart: unless-stopped
    depends_on:
      - api